language: node_js
node_js: node # latest
install: npm install
script: npm run compile
cache:
  directories:
    - node_modules
deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_success: never
  slack:
    rooms:
      secure: IC5CTJnKl9UNuurbiO7s2eKp0kB9DjH3Mo/lSXVHQrF84Eki0piiRR+Q0ru7LCiDXK2ROHQP+L0cvAtYIA0N/e64P7bjr+gA8ue0TN8QTvA6Iu6XzkuVJxb89VBTxyKiE1vxCIhLpg3n0UCcINgO10qvjumWdaWACou1kV+xpTake0+UvJv0NLvpgDVAUH5rS1leWAtOLLs+Gd8GMK9St1631XVXVJyxzr8IAYWZNhDk0ZO77oQ6YZGENm8qX5RBZ3TdbYg926yJ4N6b7k7bL2jbN9iwRPZ6YoUcti5EHW67WHcpdfM5Q53LI4tOeW1mlevOkDglzVY0fUaguURzPa1K+y4WDZ5YcwqObjkxpB04qeIIsrdwHl9B2J19+48criVsDh9u3jgCsoGlTH9954NujkUK0qtgKAe5VRH29//kBMJQAj6fMrS0VAXz4wxMFKxWjoETWsPrgq0yZ5LUHMdHBIOSiiTOL8H1k4cGGlTxkC3V9N8SyWk6t3y10pZhnCuZGtAuPj+8OuXHtxkmpMGMv6J1p6APidldCTfefM24m6H2G97CLZbxRDYHaQpyy7iNv/A4+DKXa5VthKeM4u1aEx6/zaDzpdAofARvy61NZnJz0CdUgLbYAFXGJWV1HxdlAhRKiwfOTHNMPJ0PrrAvWBTjSRRH442WmCU61wM=
